import React from "react";
import Head from "next/head";
import Image from "next/image";
import styled from "styled-components";
import tw from "twin.macro";
import Navbar from "../components/NavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Peter James Salter | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <MainStyle>
        <RainbowTitle>Welcome to PJS-Coder-Portfolio</RainbowTitle>
      </MainStyle>
      <ConditionalButton switchStyle={false}>Press Me</ConditionalButton>
    </div>
  );
}

const MainStyle = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const RainbowTitle = styled.h1`
  background: linear-gradient(
    to right,
    #ef5350,
    #f48fb1,
    #7e57c2,
    #2196f3,
    #26c6da,
    #43a047,
    #eeff41,
    #f9a825,
    #ff5722
  );
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
`;

const ConditionalButton = styled.button(({ switchStyle }) => [
  switchStyle
    ? tw`bg-[#581c87] hover:bg-[#f43f5e]`
    : tw`bg-[#0d9488] hover:bg-[#164e63]`,
  tw`
    text-slate-white
    font-bold
    py-2
    px-4
    border
    border-black
    rounded
    `,
]);
